apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.argoProjectName }}
  namespace: {{ .Values.argoNamespace }}
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: "platform project"
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"