{{- define "render-component" -}}
{{- $parent := .parent | default (dict) -}}
{{- $parentKind := $parent.kind | default "" -}}
{{- $parentName := $parent.name | default "" -}}
{{- $parentRefKey := $parent.refKey | default (printf "%sIdRef" (lower $parentKind)) -}}
{{- $kind := .kind -}}
{{- $apiVersion := .apiVersion -}}
{{- $refKey := .refKey | default (printf "%sIdRef" (lower $kind)) -}}

{{- /* Collect all ancestor references */ -}}
{{- $references := .references | default dict | deepCopy -}}
{{- if and $parentKind $parentName }}
{{- $_ := set $references $parentRefKey (trimPrefix "-" (printf "%s-%s" $parentName (lower $parentKind))) -}}
{{- end }}

{{- range $name, $config := .list }}
---
apiVersion: {{ $apiVersion }}
kind: {{ $kind }}
metadata:
  name: {{ trimPrefix "-" (printf "%s-%s-%s" $parentName $name (lower $kind)) }}
spec:
  forProvider: {{ toYaml $config.forProvider | nindent 4 }}
    {{- range $key, $value := $references }}
    {{ $key }}: {{ $value }}
    {{- end }}
{{- $dependants := $config.dependants | default dict }}
  {{- range $childKind, $childConfig := $dependants }}
{{ include "render-component" (dict "kind" $childKind "apiVersion" ($childConfig.apiVersion | default $apiVersion) "refKey" $childConfig.refKey "list" $childConfig.list "parent" (dict "kind" $kind "name" (trimPrefix "-" (printf "%s-%s" $parentName $name)) "refKey" $refKey) "references" $references) }}
  {{- end }}
{{- end }}
{{- end }}

{{- define "render-components" -}}
{{- range $kind, $config := . -}}
{{ include "render-component" (dict "kind" $kind "apiVersion" $config.apiVersion "refKey" $config.refKey "list" $config.list "parent" (dict) "references" (dict)) }}
{{- end }}
{{- end }}

{{- include "render-components" .Values.components }}