kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubeflow-proxy.fullname" . }}
  labels:
    {{- include "kubeflow-proxy.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list"]
