apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeflow-proxy.fullname" . }}
  labels:
    {{- include "kubeflow-proxy.labels" . | nindent 4 }}
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      server {
        listen {{ .Values.service.port }};
        location / {
          proxy_pass http://127.0.0.1:{{ .Values.kubectl.proxyPort }};
          # Required for WebSocket support
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
